version: 0.0
os: linux
files:
  - source: ./index.html
    destination: /var/www/html/
  - source: ./scripts/*.sh
  - destination: /home/ubuntu/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
